Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,14 +29,12 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
           
-            cd /home/ubuntu
+            cd /home/ubuntu/chat-app-backend
 
-            if [ ! -d "chat-app-backend" ]; then
-              echo "Repository not found, cloning..."
-              git clone https://github.com/yourHighness11/chat-app-backend
-            fi
-
-            cd chat-app-backend
+            # if [ ! -d "chat-app-backend" ]; then
+            #   echo "Repository not found, cloning..."
+            #   git clone https://github.com/yourHighness11/chat-app-backend
+            # fi
 
             git pull origin master
 
@@ -44,11 +42,11 @@ jobs:
 
             
             # Ensure pm2 is installed
-            if ! command -v pm2 &> /dev/null
-            then
-              echo "pm2 could not be found, installing..."
-              npm install pm2 -g
-            fi
+            # if ! command -v pm2 &> /dev/null
+            # then
+            #   echo "pm2 could not be found, installing..."
+            #   npm install pm2 -g
+            # fi
 
             # Export environment variables
             export DATABASE_URI="${DATABASE_URI}"
